### ISSUE TITLE
Windows Support?

### ISSUE THREAD

**Issue by anandsubbu007** [pr0gramista/charset_converter#13]

**Comment by arslancb** [comment]
any update on this?

**Comment by pr0gramista** [comment]
@arslancb actually yes. Just yesterday I was trying to use dart:ffi to include libiconv, but it isn't as simple as I thought.

In the next few days, I'll try to implement it natively.

**Comment by arslancb** [comment]
You are awesome @pr0gramista, I will wait.

**Comment by pr0gramista** [comment]
Hi, I just merged the PR for Windows support 🎉

I'll soon release it as version 2.1.0
