### ISSUE TITLE
encode for printing Vietnamese with esc_pos_printer

### ISSUE THREAD

**Issue by TungPT95** [pr0gramista/charset_converter#9]
could you help me which charset i can use for encoding Vietnamese text using with `esc_pos_printer`

Thanks so much

**Comment by pr0gramista** [comment]
Probably `windows-1258`, but it does actually depend on your printer so check the documentation.

**Comment by TungPT95** [comment]
i'm using xprinter N160I, it doesn't works

**Comment by pr0gramista** [comment]
Hmm interesting... Vietnamese seems to be partially (or fully?) covered by `iso-8859-1` - try that one. It may implement some characters using double byte encoding like: `AÊ` -> `Ă` and it may remap some other characters.

I found that: http://vietunicode.sourceforge.net/charset/ 

You can also try `windows-1252`.

**Comment by anhquangdev** [comment]
@pr0gramista @TungPT95 Please help me. I use [Epson TM T20II](https://files.support.epson.com/pdf/pos/bulk/tm-t20ii_trg_en_revc.pdf) to print vietnamese but it incorrect. Which charset i can use for encoding Vietnamese text, I use `package:drago_pos_printer`

**Comment by pr0gramista** [comment]
> @pr0gramista @TungPT95 Please help me. I use [Epson TM T82II](http://cdn.cnetcontent.com/16/c4/16c42bd4-83c4-4345-97d6-db8336e5d622.pdf) to print vietnamese but it incorrect. Which charset i can use for encoding Vietnamese text, I use `package:drago_pos_printer`

I think your printer supports TCVN-3, and my only guess is to try it, but it is quite miscellaneous. You can also try to map it yourself:
https://reference.epson-biz.com/modules/ref_charcode_en/index.php?content_id=40
https://reference.epson-biz.com/modules/ref_charcode_en/index.php?content_id=41

Also remember to set the code page.

**Comment by hohieuu** [comment]
hi @TungPT95 did you solve your problem and what code did you use?
